name: CI / CD

on:
  push:
    branches: [ master ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Google Cloud Functions

    steps:
    - uses: actions/checkout@v2

    - name: Setup Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SERVICE_ACCOUNT }}
        export_default_credentials: true
        
    - name: Deploy to Cloud Functions
      run: gcloud functions deploy webhook --trigger-http --allow-unauthenticated --runtime nodejs12 --region us-central1
      working-directory: functions
